import { ICourse } from "@/components/CourseCard/CourseCard";

export const AllCourses: ICourse[] = [
  {
    name: "UI/UX Design",
    img: "/assets/ui_ux_design.png",
    dollarPrice: 245.99,
    nairaPrice: null,
    level: "Beginner",
    category: "Most Popular",
    isLoved: false,
    rating: 4.9,
    noEnrolled: 100,
    field : "Design",
  },
  {
    name: "Fudamentals of UX",
    img: "/assets/ui_ux.png",
    dollarPrice: 200.99,
    nairaPrice: null,
    level: "Beginner",
    category: "Most Popular",
    isLoved: false,
    rating: 5.0,
    noEnrolled: 800,
    field : "Design",
  },
  {
    name: "Graphics Design",
    img: "/assets/graphics.png",
    dollarPrice: 150.49,
    nairaPrice: null,
    level: "Beginner",
    category: "Most Popular",
    isLoved: false,
    rating: 4.4,
    noEnrolled: 300,
    field : "Design",
  },
  {
    name: "Data Analysis for Newbies",
    img: "/assets/data_analysis.png",
    dollarPrice: 250.49,
    nairaPrice: null,
    level: "Beginner",
    category: "New",
    isLoved: false,
    rating: 4.6,
    noEnrolled: 70,
    field : "Programming",
  },
  {
    name: "Frontend Engineering",
    img: "/assets/fe_engr.png",
    dollarPrice: 305.99,
    nairaPrice: null,
    level: "Expert",
    category: "Most Popular",
    isLoved: false,
    rating: 4.8,
    noEnrolled: 490,
    field : "Programming",
  },
  {
    name: "Backend Engineering",
    img: "/assets/fe_engr.png",
    dollarPrice: 400.99,
    nairaPrice: null,
    level: "Intermediate",
    category: "Most Popular",
    isLoved: false,
    rating: 5.0,
    noEnrolled: 312,
    field : "Data",
  },
  {
    name: "Database Management",
    img: "/assets/fe_engr.png",
    dollarPrice: 380.5,
    nairaPrice: null,
    level: "Beginner",
    category: "New",
    isLoved: false,
    rating: 4.7,
    noEnrolled: 72,
    field : "Programming",
  },
  {
    name: "Figma For Devs",
    img: "/assets/fe_engr.png",
    dollarPrice: 300.49,
    nairaPrice: null,
    level: "Intermediate",
    category: "New",
    isLoved: false,
    rating: 4.9,
    noEnrolled: 122,
    field : "Design",
  },
  {
    name: "React and Redux",
    img: "/assets/fe_engr.png",
    dollarPrice: 200.49,
    nairaPrice: null,
    level: "Beginner",
    category: "New",
    isLoved: false,
    rating: 4.8,
    noEnrolled: 50,
    field : "Programming",
  },
  {
    name: "Become a MERN developer",
    img: "/assets/fe_engr.png",
    dollarPrice: 500.49,
    nairaPrice: null,
    level: "Intermediate",
    category: "New",
    isLoved: false,
    rating: 4.5,
    noEnrolled: 12,
    field : "Programming",
  },
];


export const FiltersByTime = [
    { filter: "Most Popular", isSelected : true},
    { filter: "New", isSelected : false},
 ]