
import Header from '@/components/Header/Header'
import Info from '@/components/Info/Info'
import MobileNav from '@/components/MobileNav/MobileNav'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Vephla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Info />
      <main>
        hello world fish
      </main>
    </>
  )
}
